spring:
  datasource:
    master:
      password: 112233
      url: jdbc:mysql://172.17.211.162:3306/injured_db?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave
        password: 112233
        url: jdbc:mysql://172.17.211.162:3306/db_ce_claim_new?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package:  com.injured.server.api.entity
  configLocation: classpath:mybatis/mybatis-config.xml