spring:
  redis:
    database: 0
    timeout: 1000
    host: 47.93.23.16
    password: '&_716d0LdIyb7'
    #host: 39.97.162.172
    #password: abc.123
    port: 6379
    pool:
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  datasource:
    master:
      password: 112233
      url: jdbc:mysql://47.93.254.209:3306/injured_db?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.zaxxer.hikari.HikariDataSource
    cluster:
      - key: slave
        password: 112233
        url: jdbc:mysql://47.93.254.209:3306/db_ce_claim_new?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package:  com.injured.server.api.entity
  configLocation: classpath:mybatis/mybatis-config.xml